set nocompatible                    " avoid crazy vi backwards compatibility stuff

" misc
syntax enable                       " enable syntax highlighting
set background=light                " set light background
set backspace=2                     " set backspace
set cursorline                      " highlight current cursor line
set directory=$HOME/.vim/tmp//,.    " keep swap files in one location
set expandtab                       " expand tab to spaces in insert mode
set hidden                          " nicer multiple buffer handling
set ignorecase                      " case-insensitive searching
set isk+=_,$,@,%,#,-                " mark rubyisms as keywords
set laststatus=2                    " always display status line
set list listchars=tab:\ \ ,trail:$ " show trailing whitespace
let mapleader=','                   " more accessible leader character
set number                          " show line numbers
set nobackup                        " do not make a backup before overwriting a file
set noswapfile                      " do not create swap files
set nowrap                          " do not wrap lines
set nowritebackup                   " do not make a backup before overwriting a file
set ruler                           " show cursor position
set showcmd                         " display incomplete commands
set shiftwidth=2                    " number of spaces used for each step in indentation
set showmode                        " display the current mode
set showtabline=2                   " always display tab line
set smartcase                       " case-sensitive searching when expression contains capital letters
set smartindent                     " more clever auto-indenting behavior
set smarttab                        " tabs in an indent insert 'shiftwidth' spaces
set softtabstop=2                   " number of spaces to insert for a tab
set statusline=[%n]\ %<%.99f\%h%w%m%r%y\%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l/%L,%c-%v\%)
set tabstop=2                       " number of spaces a tab stands for
set visualbell                      " use visual rather than audible bell
set wildmenu                        " command line tab completion
set wildmode=longest,full           " file name tab completion

colorscheme solarized
filetype plugin indent on           " enable filetype detection for syntax and indent rules

" use ;/: interchangably
noremap ; :

" use tab to switch to next tab
noremap <Tab> :tabn<CR>
" use shift-tab to switch to previous tab
noremap <S-Tab> :tabp<CR>

" allow the . to execute once for each line of a visual selection
vnoremap . :normal .<CR>

" keymappings for NERD tree
nmap <silent> <Leader>n :NERDTreeToggle<CR>

" jump to last known position after opening file if '" mark is set
:au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" use pathogen to handle plugins
call pathogen#runtime_append_all_bundles()

" nice auto-magic tab completion
function! SuperCleverTab()
  " check if at beginning of line
  if col('.') == 1
    return "\<Tab>"
  " check if previous character is whitespace
  elseif strpart( getline('.'), col('.')-2, 1 ) == ' '
    return "\<Tab>"
  else
    if &omnifunc != ''
      " omni-completion
      return "\<C-X>\<C-O>"
    elseif &dictionary != ''
      " dictionary completion
      return "\<C-K>"
    else
      " known-word completion
      return "\<C-N>"
    endif
  endif
endfunction
inoremap <Tab> <C-R>=SuperCleverTab()<cr>

" Source vimrc file after saving changes
" http://vimcasts.org/episodes/updating-your-vimrc-file-on-the-fly/
if has("autocmd")
  autocmd bufwritepost ~/dotfiles/lib/vimrc source $MYVIMRC
endif
