set nocompatible                    " avoid crazy vi backwards compatibility stuff

" misc
syntax enable                       " enable syntax highlighting
set autoindent                      " automatically set indent of new line
set background=light                " set light background
set directory=$HOME/.vim/tmp//,.    " keep swap files in one location
set expandtab                       " expand tab to spaces in insert mode
set hidden                          " nicer multiple buffer handling
set ignorecase                      " case-insensitive searching
set isk+=_,$,@,%,#,-                " don't use common rubyisms as word dividers
set laststatus=2                    " always display status line
set list listchars=tab:\ \ ,trail:␣ " show trailing whitespace
let mapleader=','                   " more accessible leader character
set number                          " show line numbers
set nobackup                        " do not make a backup before overwriting a file
set noswapfile                      " do not create swap files
set nowrap                          " do not wrap lines
set nowritebackup                   " do not make a backup before overwriting a file
set ruler                           " show cursor position
set showcmd                         " display incomplete commands
set shiftwidth=2                    " number of spaces used for each step in indentation
set showmode                        " display the current mode
set smartcase                       " case-sensitive searching when expression contains capital letters
set smartindent                     " more clever autoindenting behavior
set smarttab                        " tabs in an indent insert 'shiftwidth' spaces
set softtabstop=2                   " number of spaces to insert for a tab
set statusline=[%n]\ %<%.99f\ %h%w%m%r%y\ %{exists('*CapsLockStatusline')?CapsLockStatusline():''}%=%-16(\ %l,%c-%v\ %)%P
set tabstop=2                       " number of spaces a tab stands for
set visualbell                      " use visual rather than audible bell
set wildmenu                        " command line tab completion
set wildmode=list:longest           " file name tab completion

filetype plugin indent on           " enable filetype detection for syntax and indent rules

" colorscheme
" [Black, Blue, Green, Cyan, Red, Magenta, Brown, Grey, Yellow, White]
hi clear
hi Comment      ctermbg=none  ctermfg=Grey  cterm=none
hi LineNr       ctermbg=none  ctermfg=Grey  cterm=none
hi ModeMsg      ctermbg=none  ctermfg=Grey  cterm=bold
hi MoreMsg      ctermbg=none  ctermfg=Grey  cterm=bold
hi NonText      ctermbg=none  ctermfg=Grey  cterm=bold
hi Question     ctermbg=none  ctermfg=Grey  cterm=bold
hi Special      ctermbg=none  ctermfg=Grey  cterm=bold
hi SpecialKey   ctermbg=Grey  ctermfg=Black cterm=none
hi StatusLine   ctermbg=Grey  ctermfg=Black cterm=bold
hi StatusLineNC ctermbg=Grey  ctermfg=Black cterm=none
hi VertSplit    ctermbg=Grey  ctermfg=Grey  cterm=none

" use pathogen to handle plugins
call pathogen#runtime_append_all_bundles()

" LookupFile
let g:LookupFile_DefaultCmd = ':LUWalk'   " use walk by default
let g:LookupFile_MinPatLength = 2         " allow patterns of only 2 (default 4)
let g:LookupFile_ShowFiller = 0           " fix menu flashiness
let g:LookupFile_PreserveLastPattern = 0  " start with blank, rather than last pattern
